"""fixs

Revision ID: 93dd6e4db30f
Revises: 1f79b7f72195
Create Date: 2024-12-11 18:25:46.656314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93dd6e4db30f'
down_revision: Union[str, None] = '1f79b7f72195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_room_id_fkey', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    op.drop_column('bookings', 'room_id')
    op.drop_constraint('rooms_hotel_id_fkey', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'hotel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('rooms_hotel_id_fkey', 'rooms', 'hotels', ['hotel_id'], ['id'])
    op.add_column('bookings', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bookings_room_id_fkey', 'bookings', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
