"""fixs

Revision ID: eb8b89b633dc
Revises: 93dd6e4db30f
Create Date: 2024-12-14 11:46:00.638832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8b89b633dc'
down_revision: Union[str, None] = '93dd6e4db30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('room_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    op.drop_column('bookings', 'room_id')
    # ### end Alembic commands ###
