[tool.black]
line-length = 88
#extend = "linters/black.toml"
extend-exclude  = '''
    ^/(
        app/migrations
    )
'''


[tool.isort]
profile = "black"
extend_skip = ["app/migrations"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.autoflake]
check_diff = true
imports = ["sqlalchemy", "app"]


[tool.pyright]
include = ["app"]
venv = ".venv"